version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkinshome
    environment:
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
volumes:
  jenkins_home:
